Update to .net 7
exectails/Yggdrasil pull request #1
Opened 2023-05-29 22:41 UTC by makotech222

All tests are passing. 
- Switched scriptloader to use Roslyn. 
- add pragma warning ignore around using binaryserializer, which is deprecated
- update xunit

Everything else was upgraded automatically without issue

2023-05-30 07:11 UTC, exectails commented
Thank you for the pull request. It's nice to see that switching to .NET 7 was relatively straightforward. Unfortunately there's a minor issue with a straight port. I should've explained this in more detail, but I didn't expect anyone to actually go to work right away^^"

There are still Framework applications other than Melia that use Yggdrasil, and even if we switch Melia to Core, those other applications are relying on the continued support of Yggdrasil as well, and there might be no plans to switch them over. For this reason we had looked into switching to .NET Standard 2.0, for multi-framework support, or potentially cross-compile for multiple frameworks, instead of doing a straight up conversion.

Since my experience with Core and Standard are limited, perhaps you have some ideas for how to ideally go about this?

2023-06-05 09:12 UTC, exectails requested changes
Thank you for your efforts. I gave your changes a cursory look and noticed a couple (potential) issue. Btw, have you tested your updated version of Yggdrasil with Melia, or did you only run the tests for the moment?

2023-06-05 09:12 UTC, exectails commented on Yggdrasil.Scripting/ScriptLoader.cs
> -						if (mapFilePaths.TryGetValue(error.FileName, out var fileName))
Please note that it's important for the user to know where the error happened. If the script file was run through a pre-compiler, the path to the file would be somewhere in the temp folder, which is why the file name in the error was replaced here before forwarding the exception.

2023-06-05 09:12 UTC, exectails commented on Yggdrasil.Scripting/ScriptLoader.cs
> -					throw new CompilerErrorException(errors);
It appears like you removed all forwarding of exceptions or errors and are simply swallowing them now. This is a no-go, as the user needs to know that the compilation failed and why. You can see in Melia how we use this information to print out errors in scripts.

2023-06-05 09:12 UTC, exectails commented on Yggdrasil.Scripting/ScriptLoader.cs
> +			AddAssemblies(
Please try to stick to the general style conventions found around the project, such as using `this.` to access publics and prefixing private fields with `_`.

2023-06-05 09:12 UTC, exectails commented on Yggdrasil.Scripting/ScriptLoader.cs
> +				rtPath + "System.Private.CoreLib.dll",
I'd recommend refactoring this to use `Path.Combine` and to remove the manual `+ Path.DirectorySeparatorChar` above, as `Combine` will ensure that you get a valid path, regardless of different systems, frameworks, implementations, coding errors, and what have you.

2023-06-05 09:12 UTC, exectails commented on Yggdrasil.Scripting/ScriptLoader.cs
> +		private bool AddAssembly(string assemblyDll)
Please include doc comments even on private methods, as providing summaries of what methods do makes it easier to follow the code without having to read every line.

2023-06-05 09:12 UTC, exectails commented on Yggdrasil.Test/Yggdrasil.Test.csproj
> +    <PackageReference Include="xunit" Version="2.4.2" />
The xUnit update caused a bunch of compilation warnings to pop up because the new version wants things to be done differently from the old version. While warnings aren't a show-stopper, I expect Yggdrasil to compile without them. Not only because they bother me, but also because there could be some among those >100 warnings that we do care about.

2023-06-05 09:12 UTC, exectails commented on Yggdrasil.Scripting/ScriptLoader.cs
>  		/// <param name="provider"></param>
If you change signature methods, please update the comments as well. In this case for example, the parameter was removed and the summary should no longer speak of a "given compiler".

2023-06-05 09:12 UTC, exectails commented on Yggdrasil.Scripting/ScriptLoader.cs
> -		private readonly CodeDomProvider _compiler;
Letting the user specify the compiler allowed us to support different compilers, aside from C#. While losing this isn't the end of the world, it would be kind of nice to support it going forward. For example, in the past I also compiled VB.NET, Boo, and JScript with this code. Does the replacement compilation approach support this?

2023-06-05 09:12 UTC, exectails commented on Yggdrasil.Scripting/Yggdrasil.Scripting.csproj
> +    <PackageReference Include="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" Version="4.1.0" />
I'm getting a warning that `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` was made for .NET Framework and not Standard. Is this going to be an issue when using the library from a Core project?

2023-06-07 15:17 UTC, makotech222 commented
Okay just pushed a commit. Should fix all of those issues you brought up. Regarding passing in a compiler, I don 't think it really works with roslyn apis that way. It might be best to add a separate codepath for that.

2023-07-02 14:21 UTC, exectails commented
Unfortunately there are still some warnings and code convention violations. Btw, did you test this in combination with Melia yet by any chance to see if everything is working as expected?

2023-07-02 14:45 UTC, makotech222 commented
I just rebased, fixed a few compile issues in test. I'm not seeing any important warnings anymore; just a few reference conflicts, which should be fine. Any specific code convention issues?

2023-07-03 10:38 UTC, exectails commented
> Any specific code convention issues?

Particularly I noticed a few instances where the `var` keyword could be used, as well as private fields not being camelCase and prefixed with underscores.

> I'm not seeing any important warnings anymore

Warnings are rarely important but they still bug me^^ Sorry for the inconvenience.

2024-03-20 15:16 UTC, closed without merging

2024-03-20 15:16 UTC, exectails commented
Seeing how there had been some brought up issues still open, as well as more that I discovered while testing Yggdrasil with Core and Framework applications, I decided to look into updating the libraries myself, using your PR as reference. The master branch is now running on .NET Standard 2.0, and Melia will also soon be updated.

Sorry it took so long and that your efforts partially went unused, but I appreciated them nonetheless.